title: Mingyu Sang's blog
description: 백엔드 프로그래머 크로빗켄트

url: http://crobbitkent.github.com
baseurl: "/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: crobbitkent
  twitter: crobbitkent
  facebook: 
  email: crobbitkent@gmail.com
  linkedin: 

google_analytics: 

disqus:
    shortname: crobbitkent
